### ISSUE TITLE
Tests failing with Seneca@1.4.0 and 2.0.x when using Node@5

### ISSUE THREAD

**Issue by shanel262** [senecajs/seneca-web#61] opened 2016-04-25 15:28 UTC
The tests are failing when using Seneca@1.4.0 and 2.0.x with Node@5. Could be just an issue npm installing though as it complains about now being able to find lodash.
https://travis-ci.org/senecajs/seneca-web/builds/125581719

**Comment by mihaidma** [comment] 2016-04-27 13:32
assigned to @nfantone

**Comment by nfantone** [comment] 2016-04-27 18:42
I'll add that tests are also failling on recent node `6.0.0` but for different reasons.

```sh
41 tests complete
Test duration: 1096 ms
The following leaks were detected:Reflect
Coverage: 82.27% (223/1258)
// ...
Linting results: No issues

npm ERR! Test failed.  See above for more details.

```

**Comment by nfantone** [comment] 2016-04-27 18:54
Also, I can't seem to reproduce this bug locally.

```sh
nfantone@thinkpad-t430 seneca-web $ node --version
v5.11.0
nfantone@thinkpad-t430 seneca-web $ npm --version
3.8.6
nfantone@thinkpad-t430 seneca-web $ rm -rf node_modules/
nfantone@thinkpad-t430 seneca-web $ npm install
// ...
nfantone@thinkpad-t430 seneca-web $ npm test

> seneca-web@0.7.1 test /home/nfantone/dev/js/seneca/seneca-web
> lab test/*.test.js -r console -v -L -m 3000 -t 75

41 tests complete
Test duration: 1519 ms
No global variable leaks detected
Coverage: 82.27% (223/1258)
// ...
Linting results: No issues

nfantone@thinkpad-t430 seneca-web $ echo $?
0
```

**Comment by nfantone** [comment] 2016-04-27 19:10
Ok, nevermind, I was finally able to found out the culprit.

@mihaidma Do you have any idea why are we installing seneca manually:

```sh
before_script:
  - npm install seneca$SENECA_VER
```

and _also_ declare it in `devDependencies` (`"seneca": "plugin"`)? That's what's breaking stuff.

**Comment by mihaidma** [comment] 2016-04-27 20:54
in the travis file we set some seneca env variables we set two seneca versions and tests run against both of them: https://github.com/senecajs/seneca-web/blob/master/.travis.yml#L5
They run against latest seneca 1.x and latest 2.x.

After npm install we do npm install with specific seneca version. That is a trick to use a specific seneca version.

**Comment by nfantone** [comment] 2016-04-28 01:23
@mihaidma Yes, that much I gathered. My question was more into the _why_. The "trick" is breaking the build. I'm not sure of the reason behind it, but `npm` makes some packages point towards others while re-installing `seneca` (you can tell from the output log on Travis). If you just `npm install`, it works wonders.

So, the alternatives I can come up with are:

1) _Do not test against older versions of Seneca_. This isn't as inadequate as it sound. You are versioning your build script. That means that the versions of `seneca-web` that _were_ tested against `seneca` 1.x, still are and those builds can be triggered. If you want to use latest `seneca`, you should install latest `seneca-web`.

2) _Do not declare `seneca` as a dev dependency_. Just manually install the proper versions through npm scripts or Travis before running tests.

3) _Leave devDependencies as they are, but avoid installing declared seneca on Travis_. That is, leave

**Comment by mihaidma** [comment] 2016-05-09 11:09
fixed by adding an `npm uninstall seneca` before the `npm install seneca$SENECA_VER`

**Closed by mihaidma** 2016-05-09 11:09 UTC
Labels: bug

**Comment by nfantone** [comment] 2016-05-09 15:32
@mihaidma Sorry I couldn't take a look at this sooner! I was abroad and didn't find the time. This seems to work fine.
